### ISSUE TITLE
super-csv: Revert the super-csv override

### ISSUE THREAD

**Issue by arslanashraf7** [mitodl/ol-infrastructure#1006]
# User Story

This will help us remove a package override for super-csv and use the default one from edX.

# Description/Context

There were some issues with build grades due to a [CSV parser](https://github.com/openedx/super-csv) in edX and for that, we created a fix PR upstream https://github.com/openedx/super-csv/pull/100. Since we couldn't get that merged before our release so we had to override that package from our own commit. [See this PR](https://github.com/mitodl/ol-infrastructure/pull/861/files)

It's about time that the [fix PR](https://github.com/openedx/super-csv/pull/100) has been merged so we should remove our own overrided too. For that, we might just need to revert https://github.com/mitodl/ol-infrastructure/pull/861/files.

In addition, this might be something we should do with the next edX release of our MITxOnline instance.

**Checklists before doing this**
- Check the latest `super-csv` package has been published
- Check that the requirements file in edx-platform has been updated to use the latest super-csv.

# Acceptance Criteria
- [ ] package override for super-csv has been removed

**Comment by pdpinch** [comment]
@arslanashraf7 @blarghmatey does this still need to be done?

**Comment by arslanashraf7** [comment]
> @arslanashraf7 @blarghmatey does this still need to be done?

I think it does, I don't remember making any changes to the infra, The package is still running from our commit as [seen here](https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/group_data/all.py#L37).

**Comment by blarghmatey** [comment]
Yes, we haven't made any change to that yet. We can just delete that entry from the plugins once we confirm the proper version in edX.

**Comment by arslanashraf7** [comment]
@blarghmatey I circled back on this and was going to create the revert PR but I noticed a few things that I wanted to share:

1. The `residential/nutmeg` branch where we created [this PR](https://github.com/mitodl/ol-infrastructure/pull/861) doesn't exist anymore.
2. Since I wasn't seeing the revert button on the PR I guessed I might have to create a manual one for `residential/olive` but this branch also doesn't exist so I created the [revert PR](https://github.com/mitodl/ol-infrastructure/pull/1219) on `main` branch.

- Could you specify if the created PR is in the right location?
- Since this reverts the change for xPRO MITxOnline and residential, could you check if they are no by default installing [super-csv c3.0.1](https://github.com/openedx/super-csv/releases/tag/3.0.1) just to be sure that [this revert](https://github.com/mitodl/ol-infrastructure/pull/1219) would not hurt anything.

**Comment by blarghmatey** [comment]
Thanks for the detailed followup! We default to installing whichever packages are pinned in the edx-platform repository, so as long as that is set to 3.0.1 then we are all set.
