### ISSUE TITLE
Configure open edX retirement 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1007]
# User Story

As an admin, I need to be able to retire a user who requests their account be deleted. There is a management command for this. Eventually, we'd like to access this feature via API, through mitxonline and xPRO. 

See, for example, https://github.com/mitodl/mitxonline/issues/697

# Description/Context

Based on the error message:

```
[openedx.core.djangoapps.user_api.management.commands.retire_user] [user None] [ip None] retire_user.py:97 - 500 error deactivating account Default state does not exist! Populate retirement states to retire users.
CommandError: 500 error deactivating account Default state does not exist! Populate retirement states to retire users.
```

it seems that some additional configuration is necessary. 

There is a blog post that might help, at https://opencraft.com/blog/demystifying-user-retirement-in-the-open-edx-platform/

# Acceptance Criteria
- [ ] management command `retire_user` works

**Comment by blarghmatey** [comment]
Reading through the post it seems like the only thing we're missing is running the [management command](https://github.com/openedx/edx-platform/blob/open-release/nutmeg.master/openedx/core/djangoapps/user_api/management/commands/populate_retirement_states.py)

**Comment by blarghmatey** [comment]
I just ran that command against the courses-qa.mitxonline.mit.edu environment so that we can test the behavior before moving to production with it.

**Comment by blarghmatey** [comment]
It's likely that we'll need to expand on the set of states that we have configured to account for Forum at minimum.
