### ISSUE TITLE
Migrate management of Bootcamps resources into Pulumi

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1009]
# User Story
As a platform engineer I want to make sure that the Bootcamps application and its infrastructure resources are being managed in the same way as all of our other systems.

# Description/Context
The Bootcamps application was set up before our current usage of Pulumi and before we had established some of the patterns that led to the creation of the `apps` VPC. The result is that the RDS instance used in production was created in its own VPC and the Vault policies are managed via Salt code which is being actively deprecated. There are also associated S3 buckets that were created either manually or via Salt and are not being actively managed by Pulumi.

# Acceptance Criteria
- [x] Create a Pulumi project for managing the Bootcamps infrastructure resources
- [x] Either import or recreate the Bootcamps RDS instance in the applications VPC using Pulumi
- [x] Import the S3 buckets used by Bootcamps into the stack state for the Pulumi project
- [ ] Remove the associated code (e.g. Vault policies, S3 bucket management, etc.) from the salt-ops project

**Comment by mitangelo** [comment]
There should be a stack definition for each environment that the bootcamp app is deployed to (namely CI, QA, and Production). This will also need a Vault policy definition for the AWS resources that it is using and the RDS instance.
