### ISSUE TITLE
Course collection redirects

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1011]
# User Story

Out on the web, there are links to legacy course collections. We have re-created these collections on the new OCW site, but the URLs are different. 

# Description/Context

OLD: https://ocw.mit.edu/courses/energy-courses
NEW: https://ocw.mit.edu/collections/energy/

OLD: https://ocw.mit.edu/courses/entrepreneurship
NEW: https://ocw.mit.edu/collections/entrepreneurship/

OLD: https://ocw.mit.edu/courses/environment-courses
NEW: https://ocw.mit.edu/collections/environment/

OLD: https://old.ocw.mit.edu/courses/intro-programming
NEW: https://ocw.mit.edu/collections/introductory-programming/

OLD: https://old.ocw.mit.edu/courses/transportation-courses
NEW: https://ocw.mit.edu/collections/transportation/

# Acceptance Criteria

- [ ] I think these are one-off redirects to add to fastly
- [ ] test them on draft/qa and then test them on production 
- [ ] I don't think they justify automated tests, but maybe that would be a good practice exercise for #991

**Comment by pdpinch** [comment]
Ok, https://github.com/mitodl/ol-infrastructure/pull/1025 is merged. Now what? 

It doesn't seem to be active on https://live-qa.ocw.mit.edu/courses/energy-courses/ or on https:/ocw.mit.edu/courses/energy-courses/

**Comment by pdpinch** [comment]
@shaidar what's the next step?

**Comment by pdpinch** [comment]
@mitodl/devops can this be deployed to production, so https:/ocw.mit.edu/courses/energy-courses/ will redirect instead of returning a 404?

**Comment by blarghmatey** [comment]
If this has been checked on QA then we can definitely push to production. For reference, the pipeline that handles that deployment is at https://cicd.odl.mit.edu/teams/infrastructure/pipelines/pulumi-ocw-site

**Comment by pdpinch** [comment]
As far as I can tell, these all work fine now.
