### ISSUE TITLE
Two YouTube playlist redirects 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1012]
# User Story

Gil Strang is working on the latest edition of his Linear Algebra textbook and has asked me if we can create more redirects so that readers can get to his YouTube Playlists using a simple URL. 

He is now requesting redirects to these two playlists on YouTube
• RES.18-010 A 2020 Vision of Linear Algebra https://www.youtube.com/playlist?list=PLUl4u3cNGP61iQEFiWLE21EJCxwmWvvek

• 18.065 Matrix Methods in Data Analysis, Signal Processing, and Machine Learning
https://www.youtube.com/playlist?list=PLUl4u3cNGP61iQEFiWLE21EJCxwmWvvek

# Acceptance Criteria
- [ ] follow the existing practice or YouTube collection redirects to add these two to the fastly config

**Comment by shaidar** [comment]
@pt2302 This should be now deployed to live and draft QA if u want to verify expected behavior before I go ahead and deploy it to production

**Comment by pt2302** [comment]
@shaidar Thank you. Verified.

The following redirect as expected:

https://draft-qa.ocw.mit.edu/2020-vision-videos
https://live-qa.ocw.mit.edu/2020-vision-videos

https://draft-qa.ocw.mit.edu/2018-matrix-methods
https://live-qa.ocw.mit.edu/2018-matrix-methods

https://draft-qa.ocw.mit.edu/2018-matrix-methods-videos
https://live-qa.ocw.mit.edu/2018-matrix-methods-videos

**Comment by shaidar** [comment]
Deployed to production.

**Comment by pt2302** [comment]
Verified in production.
