### ISSUE TITLE
setup 2FA for TechTV YouTube account

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1066]
# User Story

Elaine would like to stop getting notified whenever we need to log in to the TechTV YouTube account. 

As a devops, I'd like a known reliable way to log into this account that doesn't involve tracking down someone else's phone. 

# Description/Context

- [ ] Does YouTube log in support TOTP instead of / in addition to SMS?
- [ ] Does LastPass support (shared) TOTP? 

# Acceptance Criteria
- [ ] log in to the account without involving anyone besides devops

**Comment by blarghmatey** [comment]
@shaidar did this get taken care of as part of the LastPass migration into Vault?

**Comment by shaidar** [comment]
My phone is now the second factor and Tobias is setup as the recovery. I also added account username, pass and some metadata in vault for this under techtv.

**Comment by pdpinch** [comment]
Did you let Elain know?

**Comment by shaidar** [comment]
Yes, I was working with her to login to the account.
