### ISSUE TITLE
back-populate persistent grades for two courses

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1076]
# User Story
- The gradebook is all zeroes for `course-v1:MITxT+14.310x+1T2022` and `course-v1:MITxT+JPAL102x`

- https://courses.mitxonline.mit.edu/gradebook/course-v1:MITxT+14.310x+1T2022
- https://courses.mitxonline.mit.edu/gradebook/course-v1:MITxT+JPAL102x+1T2022

At least [one user has written in](https://odl.zendesk.com/agent/tickets/133561) to report their grades are incorrect. 

# Description/Context

A couple of weeks ago, we turned on persistent grades and ran a management command that was supposed to back-populate the grades. It doesn't seem to have completed successfully. 

In at least one case, it has worked OK to run the same management command targeted at the course in question. 

# Acceptance Criteria

- [x] Run the management command for `course-v1:MITxT+14.310x+1T2022` and `course-v1:MITxT+JPAL102x`
- [x] Confirm that at least some of the grades are getting populated (the speed and sequence is unpredictable)
- [x] Confirm that the user in [ZenDesk 133561](https://odl.zendesk.com/agent/tickets/133561) had a grade in each course.  
- [ ] How/can we determine if there are other courses in this state?

**Comment by blarghmatey** [comment]
I unfroze the grades for the two courses in question and verified that the persisted grades are being updated. As to determining whether other courses are in this state, I ran a query to identify how many persisted grades are present for the courses represented in the `grades_persistentcoursegrade` table so that we can check that against courses that we expect to be represented.

**Comment by blarghmatey** [comment]
The steps to override the frozen grades were pulled from https://github.com/openedx/edx-platform/blob/master/lms/djangoapps/grades/docs/how_tos/how-to-regrade-everyone-in-a-course.rst

**Comment by pdpinch** [comment]
I think I got the same advice from Pierre on my forum post: https://discuss.openedx.org/t/challenges-with-turning-on-persistent-grades/8318/3

**Comment by blarghmatey** [comment]
@pdpinch is this clear to close now?

**Comment by pdpinch** [comment]
These two courses now at least have _some_ grades. It's hard to tell if they are complete since so many learners who enrolled never submitted to any problems. 

> I ran a query to identify how many persisted grades are present for the courses represented in the grades_persistentcoursegrade table so that we can check that against courses that we expect to be represented.

Can you remind me where I can see the results of this query?

**Comment by pdpinch** [comment]
No one has complained about this lately, so I'm going to assume we did enough.
