### ISSUE TITLE
Add a schedule trigger for MITx Online deploys to production

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1088]
We are ready to start deploying Open edX for MITx Online on a weekly basis on Wednesdays. We need to add a schedule trigger to the production stage of the relevant pipelines. This includes the edx-platform instance, the MFEs being used (learn and gradebook at the moment), and Forum.

**Comment by pdpinch** [comment]
@blarghmatey is this still relevant, given that we want the Wednesday deployment to production to be discretionary, based on the MITx EdTech teams's input?
