### ISSUE TITLE
Alert on "invalid username and password" 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1138]
# User Story

We were alerted by the OCW team that publishing courses was failing. We should know when this happens before they alert us. 

# Description/Context

Our concourse alerts on publish failures didn't catch this because the publish failed before it could connect to concourse

https://sentry.io/organizations/mit-office-of-digital-learning/issues/3668240004/?project=5739976&query=is%3Aunresolved

# Acceptance Criteria
- [ ] Alert when there is a credential issue in a way that SRE can fix it asap

**Comment by Ardiea** [comment]
@pdpinch I let this ticket linger for too long and the log examples expired out of grafana but I did implement one based on the code you linked that should get the job done. 

https://github.com/mitodl/grafana-alerts/commit/e577cd9a41756f5b7cc63e76fcf8a10b77bd2523
