### ISSUE TITLE
Allow Dagster to communicate securely with our Airbyte installation

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1140]
# User Story
As a data engineer I want to be able to connect from Dagster to the Airbyte API to manage connection syncs and introspect the data assets that it generates.

# Description/Context
There are two issues that we are running into currently.
- By default we are using the Consul address for connecting from Dagster -> Airbyte (`airbyte.service.consul`). This can't currently happen via HTTPS because the certificate doesn't contain that hostname, and Dagster doesn't have an option for ignoring invalid (e.g. self-signed) certificates. We can solve this by one or both of:
  - Update the Airbyte integration to accept "invalid" certificates
  - Update the certificate being generated to include the Consul hostname
- The Airbyte integration for Dagster doesn't currently support authentication in the connection details. We can work around this by embedding the basic auth in the host string (e.g. `host=user:password@airbyte.service.consul`), but it would be good if we can update the integration to support this out of the box.

I have created an issue in the upstream repository https://github.com/dagster-io/dagster/issues/9995

# Acceptance Criteria
- [ ] The Airbyte -> dbt pipelines that are currently deployed to QA are able to function with our installation of Airbyte

**Comment by shaidar** [comment]
We are currently not generating a cert and just using the [odl wildcard one](https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/components/pomerium/models.py#L22). Looking into what's involved in using lets encrypt and generating a cert as part of the image build.
