### ISSUE TITLE
YouTube redirect for 24.908

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1155]
# User Story

Users who watch the videos in the [24.908 collection](https://www.youtube.com/playlist?list=PLUl4u3cNGP62-sHzh435NhKGnwOkPYk36) want to be able to link through to the OCW site. 

The link in the description is a short URL, https://ocw.mit.edu/24-908S17 in their description

# Acceptance Criteria
- [ ] redirect the URL (not path) https://ocw.mit.edu/24-908S17 to https://ocw.mit.edu/courses/24-908-creole-languages-and-caribbean-identities-spring-2017/

**Comment by shaidar** [comment]
Deployed to QA live and draft.

**Comment by pt2302** [comment]
@shaidar Thank you. Verified.

The following redirect as expected:

https://draft-qa.ocw.mit.edu/24-908S17/
https://live-qa.ocw.mit.edu/24-908S17/

**Comment by shaidar** [comment]
Deployed to production live and draft.
