### ISSUE TITLE
YouTube redirect for highlights of calculus 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1156]
https://www.youtube.com/playlist?list=PLBE9407EA64E2C318

# User Story

Users who watch the videos in the [Highlights of Calculus collection](https://www.youtube.com/playlist?list=PLBE9407EA64E2C318) want to be able to link through to the OCW site. 

The link in the description is a short URL, https://ocw.mit.edu/highlights-of-calculus in their description

# Acceptance Criteria
- [ ] redirect the URL (not path) https://ocw.mit.edu/highlights-of-calculus to https://ocw.mit.edu/courses/res-18-005-highlights-of-calculus-spring-2010/

**Comment by shaidar** [comment]
Deployed to QA live and draft.

**Comment by shaidar** [comment]
Deployed to production draft and live

**Comment by pt2302** [comment]
Verified in production.
