### ISSUE TITLE
olive: enable in-course search for xPRO and Residential MITx

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1183]
# User Story

As a user, I'd like to be able to search for a string while I am in a course, and find the page where the string is used. 

# Description/Context

According to https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/edx_search.html#enable-indexing all we may need to do is:

- [x] set ` ENABLE_COURSEWARE_INDEX` to true
- [x] set `SEARCH_ENGINE`
- [x] set `ENABLE_COURSEWARE_SEARCH` to true

Note that we don't need to turn on `ENABLE_DASHBOARD_SEARCH` and we **don't want to turn on** `ENABLE_COURSE_DISCOVERY` 

# Acceptance Criteria
- [ ] 

Something like this (screenshot from sandbox.openedx.org): 

![image](https://user-images.githubusercontent.com/430126/199101451-a0cd6678-8b49-488c-a8af-06e9fae4a0fc.png)

**Comment by blarghmatey** [comment]
The necessary configuration settings have been populated, and reindexing from studio is functional. Unfortunately I don't see any search interface in the learner MFE. Is it possible that feature never got ported to the new interface? It's also possible that there's another configuration variable that needs to be set in the MFE build to expose the search box.

**Comment by pdpinch** [comment]
[According to Adolfo, there is no support for this](https://discuss.openedx.org/t/does-the-learning-mfe-support-courseware-search/8807). We'll consider taking it up based on priority.
