### ISSUE TITLE
olive: set up discussion notifications 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1184]
# User Story

- As a user, I'd like to get email notifications when someone replies to my discussion post

# Description/Context

- [x] deploy and set up [ACE application](https://edx-ace.readthedocs.io/en/latest/)
- [x] determine if this requires additional email infrastrcture or if we can use existing django/mailgun integrration
- [ ] turn on [discussion notifications](https://edx.readthedocs.io/projects/edx-installing-configuring-and-running/en/latest/configuration/enable_discussion_notifications.html#id14)
  - [x] CI
  - [ ] QA
  - [ ] Production

# Acceptance Criteria
- [ ] 

1. Make a discussion post
2. Ask someone else to comment on it
3. you should receive an email notification about the response to your post

**Comment by blarghmatey** [comment]
I created the relevant site config in the CI environment. This is ready to test.

**Comment by pdpinch** [comment]
According to @cachob this is working
