### ISSUE TITLE
Open edX Olive Waffle Flags

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1201]
As we work through the Olive release of Open edX there are a number of waffle flags that need to be set to enable various features and MFE applications. This issue tracks those values to ensure they get propagated to subsequent environments.

# xPro

# Residential

# Common
- ORA Grading MFE flag: [openresponseassessment.enhanced_staff_grader](https://github.com/edx/frontend-app-ora-grading)
- Course Authoring MFE: ([docs](https://github.com/openedx/frontend-app-course-authoring/pull/381))
  - `new_core_editors.use_new_text_editor`: must be enabled for the new HTML Xblock editor to be used in Studio
  - `new_core_editors.use_new_video_editor`: must be enabled for the new Video Xblock editor to be used in Studio
  - `new_core_editors.use_new_problem_editor`: must be enabled for the new Problem Xblock editor to be used in Studio
  - `discussions.pages_and_resources_mfe`
- Library authoring MFE: `studio.library_authoring_mfe`

**Comment by pdpinch** [comment]
I have turned off `new_core_editors.use_new_text_editor`, `new_core_editors.use_new_video_editor` and `new_core_editors.use_new_problem_editor` on courses-ci.xpro.mit.edu. The new interfaces don't work well enough to justify having them on, anywhere in xPRO. 

I'm not sure what Residential MITx's preference might be.

**Comment by pdpinch** [comment]
Before I forget, there's a flag for enabling scheduling (i.e. the Dates Tab). It might already be set in production, but it wasn't set on CI
