### ISSUE TITLE
Enable fastly logging for OCW

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-infrastructure#1224]
# User Story
- We need to enable logging on Fastly to get a sense of how much usage is the download course content feature is getting.

# Description/Context

For now, it's good enough to simply enable logging and collect the data in S3 for later analysis.

# Acceptance Criteria
- [ ]

**Comment by Ardiea** [comment]
https://www.pulumi.com/registry/packages/fastly/api-docs/servicevcl/#servicevclloggingsftp
