### ISSUE TITLE
Discussion doesn't load on xPRO CI 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1232]
See https://courses-ci.xpro.mit.edu/learn/course/course-v1:XPRO+TESTING+TESTR0/block-v1:XPRO+TESTING+TESTR0+type@sequential+block@6c4c5087b1254a4c85681f45e10614dc/block-v1:XPRO+TESTING+TESTR0+type@vertical+block@b2d3263c879749cdb68bff89699528f5

Looks like a 400 error from https://courses-ci.xpro.mit.edu/courses/course-v1:XPRO+TESTING+TESTR0/discussion/forum/6d63e4be6faf55d2d841d0aa54f03cf2459ea41e/inline?page=1&sort_key=activity&sort_order=desc&ajax=1

![image](https://user-images.githubusercontent.com/430126/204363837-a37a4302-3440-45ed-9160-3e12af9023e2.png)

**Comment by pdpinch** [comment]
The Discussion tab is also failing: https://courses-ci.xpro.mit.edu/courses/course-v1:XPRO+TESTING+TESTR0/discussion/forum/

**Comment by blarghmatey** [comment]
This is an odd error. In https://courses-ci.xpro.mit.edu/learn/course/course-v1:MITx+DigitalLearning200+Jan_2016/home I am able to see the discussion tab and load it without issue. I was also able to submit a post in that course.

Is it possible that the error for the course you linked is in the course configuration?

**Comment by pdpinch** [comment]
I'm getting a similar error on https://courses-ci.xpro.mit.edu/learn/course/course-v1:MITx+DigitalLearning200+Jan_2016/home 

![image](https://user-images.githubusercontent.com/430126/204655604-fb776c15-e1d6-436f-9d05-b91bf6087c72.png)

Maybe it has something to do with my user? https://sentry.io/organizations/mit-office-of-digital-learning/issues/3773663487/?environment=xpro-ci&project=1730882&query=is%3Aunresolved&referrer=issue-stream

**Comment by cachob** [comment]
I clicked on the links that failed for @pdpinch and was able to see the pages with no errors
