### ISSUE TITLE
Regression: redirect for OCW Scholar Course collection

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1369]
- https://github.com/mitodl/ol-infrastructure/issues/1221 was working but isn't now

# Description/Context

This was fixed in https://github.com/mitodl/ol-infrastructure/pull/1225/commits/3e2a9d0ee7d977198599c6c908b246455e92cf29 with this code:

https://github.com/mitodl/ol-infrastructure/blob/ed9ee6806f27806f3c5a06740485b44d74e8a532/src/ol_infrastructure/applications/ocw_site/redirect_dict.json#L475

but it's not working now. 

```
curl -I https://ocw.mit.edu/courses/ocw-scholar/              
HTTP/2 404 
retry-after: 0
content-type: text/html
accept-ranges: bytes
date: Fri, 17 Feb 2023 22:06:01 GMT
x-served-by: cache-bos4658-BOS
x-cache: MISS
x-cache-hits: 0
strict-transport-security: max-age=300
content-length: 2824
```

# Acceptance Criteria
- [ ] Please, make it work!

**Comment by blarghmatey** [comment]
I'm pretty sure the issue is that it has the trailing `/` so it falls through to one of the other pieces of logic. I think the whole redirect dictionary logic is due for a refactor that meets our current needs, rather than continuing to cargo-cult the old syntax and assumptions.

**Comment by blarghmatey** [comment]
@pdpinch is this still an active issue?

**Comment by pdpinch** [comment]
It works without the slash. I'll double-check on the user story to see what's needed. 

```
pdpinch@pdpinch2018 open-discussions % curl -I https://ocw.mit.edu/courses/ocw-scholar  
HTTP/2 301 
retry-after: 0
location: https://ocw.mit.edu/courses/ocw-scholar/
accept-ranges: bytes
date: Wed, 31 May 2023 15:11:38 GMT
x-served-by: cache-lga21936-LGA
x-cache: HIT
x-cache-hits: 0
strict-transport-security: max-age=300
content-length: 0
```

**Comment by pdpinch** [comment]
Ah no, that's a false positive. the 301 leads to a 404.

**Comment by HussainTaj-arbisoft** [comment]
@blarghmatey is right. It's a trailing `/` issue.

The URL `https://ocw.mit.edu/courses/ocw-scholar//` works.

```bash
❯ curl -I https://ocw.mit.edu/courses/ocw-scholar//
HTTP/2 307
retry-after: 0
location: https://ocw.mit.edu/course-lists/scholar-courses/
accept-ranges: bytes
date: Fri, 02 Jun 2023 09:29:51 GMT
x-served-by: cache-fjr990027-FJR
x-cache: HIT
x-cache-hits: 0
strict-transport-security: max-age=300
content-length: 0
```

**Comment by HussainTaj-arbisoft** [comment]
I scanned the redirect config for similar URL issues and found https://ocw.mit.edu/courses/12-003-atmosphere-ocean-and-climate-dynamics-fall-2008/resources/lab11/experiment-xi-baroclinic-instability-of-the-thermal-wind/. All other URLs are correct.

I will add the fix for it in the same PR.
