### ISSUE TITLE
Automate bootcamps and micromasters credential management in redash 

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1371]
We should automate the credential refresh for micromasters and bootcamps in the redash configs. Right now the credential providers are disabled in vault, so we can't but at some point BC + MM will be following the standard pattern and those providers should be back. When that time comes we can action this issue and add those two providers here: 

https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/redash/files/datasources.yaml.tmpl

and update the vault role of the redash nodes here:

https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/redash/redash_server_policy.hcl

And any misc data needed like the dbhost name goes into consul

https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/redash/__main__.py#L310-L359

**Comment by blarghmatey** [comment]
Micromasters is being migrated to use the same pattern as our other sources and can be updated to automate credentials once that has been deployed to production, likely next week. Bootcamps should be following along shortly afterwards.

**Comment by blarghmatey** [comment]
Once #1009 is complete this will be unblocked.
