### ISSUE TITLE
Retire Heroku OVS CI instance / Create AWS OVS CI Instance

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-infrastructure#1372]
# User Story

OVS RC and Production instances run on AWS EC2 instance. However, OVS CI is still running in Heroku and needs to be migrated to AWS.
# Description/Context

Dump/load the data and then update the Concourse pipeline to manage the build/deployment of the container and AMI for CI whenever there's a new commit on master.
# Acceptance Criteria

- [ ] Data in current Heroku CI app has been migrated
- [ ] Commit to master branch of https://github.com/mitodl/odl-video-service triggers a build and deploy in Concourse
- [ ] CI app is accessible at previous URL

**Comment by blarghmatey** [comment]
@Ardiea is this ready to be closed?
