### ISSUE TITLE
Send Fastly logs into Grafana for debugging and alerting

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1414]
# User Story
- As a platform engineer I would like to be alerted when a Fastly property is experiencing a spike of error conditions
- As an application engineer I would like to be able to diagnose errors all the way from Fastly through to the backend system

# Description/Context
We need a path for sending Fastly logs into a data source connected to Grafana. The most likely destination is to use Vector as a router for proxying log data into the Grana cloud managed Loki storage system.

# Acceptance Criteria
- [ ] Fastly properties all log as JSON to S3 with a standard message schema
- [ ] Fastly logs are sent to Loki via a Vector proxy using HTTPS or ~Syslog inputs~ absolutely not. 
- [ ] Vector rejects log data generated by bot traffic as identified by user agent information
- [ ] Fastly logs are available in grafana via the established Loki datasources

**Comment by Ardiea** [comment]
I will need to put nginx in front of vector https listener (not currently doing that).

https://docs.fastly.com/en/guides/log-streaming-https#prerequisites

> When sending logs to a HTTPS endpoint, Fastly requires proof that you control the domain name specified in the URL field by using a HTTP challenge on a [well-known path](https://datatracker.ietf.org/doc/html/rfc8615#section-1). If, for example, your URL field is foo.example.com/some/log/path, then the following challenge path must send a 200 response:
> foo.example.com/.well-known/fastly/logging/challenge
> Responses must include the hex representation of the SHA-256 of your Fastly service ID and it must appear on its own line in the response.

**Comment by blarghmatey** [comment]
s/nginx/traefik/

**Comment by Ardiea** [comment]
Mmm. Nope. Traefik isn't actually a web server. Reverse proxy / lb only and I need to serve up 1 static file to answer the challenge from fastly (the hashed service ID). So I can do traefik and have it route based on path but I'll still need nginx or something similar to actually serve the file. 

Above is actually not dissimilar to some of the only prior art I've found on this subject: https://tech.loveholidays.com/realtime-fastly-logs-with-grafana-loki-for-under-1-a-day-5b63ccf32d66

replace GKE Ingress with Traefik and fluentbit with vector. 


We can also simplify the design by switching to syslog, despite my vehement opposition which doesn't actually have much grounding behind it. We will need to do mutual TLS though, which is its own can of worms to figure out but not insurmountable now that we have PKI stuff in place. 

I could go either way, they are both interesting to me. Prob nginx proxy gets the task done quicker and on to the next thing and it isn't too much of a deviation from the current implementation for logplex + heroku already in place.
