### ISSUE TITLE
Constrain Airbyte worker memory to fraction of host total

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1502]
# Description/Context
The production Airbyte server is getting crushed by memory pressure due to the connector images being free to use as much memory as they want. We want to set the `JOB_MAIN_CONTAINER_MEMORY_LIMIT` environment variable to be approximately 1/6th of the total host memory.

This can probably be done most easily by writing a small script that gets run by cloud-init at launch to write the desired value into an `/etc/default/` file path to be consumed by consul-template.

# Acceptance Criteria
- [ ] Airbyte doesn't get crushed by memory pressure any more

**Comment by Ardiea** [comment]
This is more complicated than it appears on the surface. 

You can't set env vars equal to the output of a shell expression in the .env or in docker-compose.yml, not allowed.

You also can't do the same with `/etc/default/consul-template` as suggested in the description. What you can do, is create a fully static `/etc/default/consul-template` file using an `ExecStartPre="/bin/sh echo "$(shell code to generate env var + value)" > /etc/default/consul-template"` 

And then in the consul template for `.env.` you should be able to do something like `JOB_MAIN_CONTAINER_MEMORY_LIMIT={{ env "NAME_OF_THE_VAR_YOU_CREATED_IN /etc/default/consul-template" }}

**Comment by blarghmatey** [comment]
This was a red herring and is no longer blocking our use of Airbyte.
