### ISSUE TITLE
Upgrade Hugo and Go in ocw-course-publisher Docker image

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ol-infrastructure#1513]
# User Story
In [Hugo v0.111.0](https://github.com/gohugoio/hugo/releases/tag/v0.111.0), a global `page` func was added that allows you to obtain the `Page` context globally. This will allow us to refactor a lot of code in `ocw-hugo-themes` that plays "context hot potato" by passing the page context to any partials called in a template, then having to pass that context to any partials called there and so-on.

# Description/Context
We should update Hugo to the latest version, as well as the latest version of `go` 1.18 in `dockerfiles/ocw/node-hugo/Dockerfile` and up the version number. After this is done, an issue should be created in `ocw-studio` to update the pipeline definitions there to use the latest version of the Docker image.

# Acceptance Criteria
- [ ] Hugo updated
- [ ] Go updated
- [ ] Version bumped

**Comment by HussainTaj-arbisoft** [comment]
[0.112.0](https://github.com/gohugoio/hugo/releases?q=v0.112.0&expanded=true) was released a few hours ago. I don't think any of the primary changes affect us so we're good to use that version.
