### ISSUE TITLE
Create Concourse pipeline for building and publishing edX Forum container

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#163]
In order to simplify deployment and management of the edX Forum application we would like to run it in a container. To make this possible we need to develop a Dockerfile and associated Concourse pipeline to build the container and publish it to a container registry.

**Comment by blarghmatey** [comment]
We can crib from the Dockerfile in Tutor for forum [here](https://github.com/overhangio/tutor/blob/master/tutor/templates/build/forum/Dockerfile) to figure out a working solution for our deployment.

**Comment by mitangelo** [comment]
WIP....
