### ISSUE TITLE
instance refreshes for ocw concourse workers 

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1630]
# Description/Context

There is something up with OCW concourse workers that causes they to use up their somewhat generous disk allotment and never reclaim it back. The monitoring has been fixed but the alerting still didn't go off.

Additionally, it is sending it too much data (every virtual disk matching the same device) comes in leading to many many time series of data that are essentially duplicates. So figure that out too. Just one filesystem is good, not all filesystem.

**Comment by pdpinch** [comment]
Does the instance refresh interrupt users in some way? 

Unless there's a really good reason (like interrupting users), I prefer scheduled tasks to run during work hours so any issues that arise get noticed and dealt with.

**Comment by Ardiea** [comment]
It could potentially cause disruptions to users. There are a lot of variables involved and the chances are low, but it could happen.
