### ISSUE TITLE
Downgrade mitodl Github account to support new Merge Queue feature

### ISSUE THREAD

**Issue by feoh** [mitodl/ol-infrastructure#1631]
# Description/Context

Investigate whether our account needs to be upgraded from 'Legacy' status in order to support the merge queue feature detailed [here](https://github.blog/2023-07-12-github-merge-queue-is-generally-available/).

# Plan/Design
(This section needs to be fleshed out)

- Investigate necessary changes
- Profit

**Comment by shaidar** [comment]
Currently when we go to a repo's branch protection rules, we don't see an option to [`Require Merge Queue`](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches#require-merge-queue). Based on GitHub documentation that should be available to all new [GitHub plans](https://docs.github.com/en/get-started/learning-about-github/faq-about-changes-to-githubs-plans). At least that's what the Github documentation suggests in the screenshot below. 

![Screenshot 2023-08-04 at 9 36 04 AM](https://github.com/mitodl/ol-infrastructure/assets/1447295/7c1ecd5d-c089-4d1b-a2ac-c1ef037fbf6b)

Based on that information and taking into consideration our current usage, we should be able to downgrade our legacy plan to the free one - https://github.com/organizations/mitodl/billing/plans. Once that switch is flipped, we should be able to then make use of the merge queue feature.

Planning on flipping that switch on Monday, August 7th, 2023.

**Comment by shaidar** [comment]
As part of the downgrade, the following will be impacted:
<img width="435" alt="Screenshot 2023-08-07 at 8 46 07 AM" src="https://github.com/mitodl/ol-infrastructure/assets/1447295/4f01178d-6e22-4f2b-b71c-e42b409e10e1">

**Comment by shaidar** [comment]
Downgraded plan and it will not take effect till after August 15th, 2023.

**Comment by pdpinch** [comment]
Ok. Can you remind us of that on 8/15, in case anything starts behaving unexpectedly?

**Comment by shaidar** [comment]
We haven't run into any issues related to this so far. I have checked and notified the group that the merge queue feature is now available. Will leave this issue open for another week just to make sure that we haven't lost any functionality and then close it out.

**Comment by shaidar** [comment]
No issues so far so will close this.
