### ISSUE TITLE
Update Mailgun API keys

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#1666]
# Description/Context

Mailgun has added some new security features to its API keys. We should consider upgrading our keys. 

<img width="613" alt="image" src="https://github.com/mitodl/ol-infrastructure/assets/430126/a19ba57b-76b1-42b5-ba4e-d3e19db2d196">

# Plan/Design

tbd

**Comment by shaidar** [comment]
What is referenced in our repos and we refer to as `MAILGUN_KEY` (ex. [here](https://github.com/mitodl/mitxonline/blob/main/main/settings.py#L495-L499)) is in fact the "[HTTP webhook signing key](https://documentation.mailgun.com/en/latest/api-webhooks.html#webhooks)" and not the "[Verification public key](https://documentation.mailgun.com/en/latest/api-email-validation.html#email-verifications)" which is being replaced by Mailgun's new API key management feature. 

Based on looking through a few of our repos, we currently do not use that feature in Mailgun and rely on Django's [validators](https://docs.djangoproject.com/en/4.2/ref/validators/) for that functionality (example from [mitxonline](https://github.com/mitodl/mitxonline/blob/main/mail/api.py#L31)).

At this point, I don't believe there's anything for us to do on this issue.
