### ISSUE TITLE
Upgrade pulumi-aws to V6

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1744]
# Description/Context
The v6 release of the Pulumi AWS provider has some breaking changes that we need to review and address during the upgrade.

# Plan/Design
Review the related Renovate PR here: https://github.com/mitodl/ol-infrastructure/pull/1733
- Review related changelog documentation and upgrade instructions
- Apply required changes or open specific issues to address relevant changes

**Comment by Ardiea** [comment]
https://www.pulumi.com/registry/packages/aws/how-to-guides/6-0-migration/

https://www.pulumi.com/blog/announcing-6-0-of-the-pulumi-aws-classic-provider/
