### ISSUE TITLE
Review and update RATELIMIT settings for xPro

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1755]
## Description
Verify that ratelimits are as they should be for xpro-edxapp.

They go here: https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp_v2/templates/edxapp/xpro/lms_only.yml.tmpl#L86

Relates to https://github.com/mitodl/hq/issues/2367 

See: 

https://docs.openedx.org/projects/edx-platform/en/latest/references/settings.html#setting-RATELIMIT_RATE

**Comment by pdpinch** [comment]
Can we do this as part of the Quince upgrade?

**Comment by asadali145** [comment]
Rate limits look good to me. We have set good enough values for all required. We could reduce REGISTRATION_RATELIMIT and REGISTRATION_VALIDATION_RATELIMIT a bit if we want. Here are the details:

RATELIMIT_RATE `edX: 120/m`, `xPro: 600/m`
REGISTRATION_RATELIMIT `edX: 60/7d`, xPro: `1000000/minute`
REGISTRATION_VALIDATION_RATELIMIT `edX: 30/7d`, `xPro: 1000000/minute`

**Comment by pdpinch** [comment]
I'm assuming this is good now
