### ISSUE TITLE
Provide a simple onboarding flow for users to backend services

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1799]
# User Story

- As a platform owner I want to reduce the maintenance burden of onboarding new users
- As an end user of platform components I want an easy way of getting access to our various services

# Description/Context

Since we are investing in Keycloak as our supported SSO solution it would be useful to use that as the means of granting access to users of our various platform components. Examples of services that would benefit from enabling SSO include:
- Trino
- Superset
- OpenMetadata (not yet implemented)

The main groupings of people who we want to be able to support are engineers internal to our team, or MIT employees who are non-engineers. To address that cross-section of users the most likely approach would be to combine Touchstone/SAML for authentication with LDAP for authorization.

# Acceptance Criteria

- [x] Touchstone SAML is enabled on the Keycloak realm used to authenticate to the different platform components
- [ ] Keycloak is configured to be able to communicate with the MIT LDAP server
- [ ] A meaningful set of Moira groups are configured that we can map to appropriate roles in the target platforms

# Plan/Design

My ideal case is that we can combine the Touchstone AuthN with LDAP for AuthZ, such that when a user logs into a given service it maps them to an appropriate role based on their LDAP group membership. For example, if someone logs into Starburst Galaxy then we can grant the user to the marketing role because they belong to the `ol-data-marketing` moira group.

**Comment by shaidar** [comment]
Read through some kb articles on options for using ldap or kerberos for authorization in Keycloak and then had a conversation with IST. Their idea is that Touchstone can also be used as part of authorization along with leveraging existing Moira groups. They would need to release `memberOf` attribute and we'd have to handle some mapping on the Keycloak end and based on that allow or disallow access. This will need quite a bit of testing and some Keycloak config, but it's worth trying out as it'll be simpler than adding ldap or some other additional provider for authn.

**Comment by shaidar** [comment]
Submitted request to IST with relevant details to test on the ol-engineering realm in CI. The memberOf attribute released will filter on groups starting with `ol-*` in Moira.

**Comment by shaidar** [comment]
[To exchange group and user information with Starburst](https://docs.starburst.io/starburst-galaxy/sso/okta-scim-setup.html), we need to install and configure a SCIM plugin for Keycloak. A [SCIM plugin](https://scim-for-keycloak.de) exists (free and enterprise license available) and will work on installing and testing it out. One downside so far is that the download is manual and so is obtaining a free or paid license.

**Comment by shaidar** [comment]
The previous [plugin](https://scim-for-keycloak.de/) is a SCIM server which is the reverse of what we need. They are currently working on a client, but is not available as of now. We came across a [SCIM client ](https://lab.libreho.st/libre.sh/scim/keycloak-scim), however it fails on build:
```
ERROR: Failed to run 'build' command.
ERROR: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step org.keycloak.quarkus.deployment.KeycloakProcessor#configureKeycloakSessionFactory threw an exception: java.util.ServiceConfigurationError: org.keycloak.storage.UserStorageProviderFactory: Provider sh.libre.scim.storage.ScimStorageProviderFactory could not be instantiated
```

Checked the repo to see if anyone reported the same or similar problem, but the project is a year old and not sure how well maintained it is. I did come across an [issue](https://github.com/keycloak/keycloak/issues/13484) on the Keycloak repo about integrating a SCIM client into upstream and there seems to be some interest, however it hasn't happened yet.

**Comment by shaidar** [comment]
Ended up forking the [repo](https://lab.libreho.st/libre.sh/scim/keycloak-scim) and merging a [PR](https://lab.libreho.st/libre.sh/scim/keycloak-scim/-/merge_requests/2) that updated the dependencies and replaced some functionality with the [other scim library](https://scim-for-keycloak.de/).
Used Gradle to create a new JAR file and ran the keycloak build command with the new JAR and it ran through showing that the new provider was loaded. Didn't check the UI, but technically should be working now. Updated Keycloak pipeline to include this new plugin and will test functionality on CI.

**Comment by FrancescoErmini** [comment]
Any update on SCIM implementation or roadmap?
