### ISSUE TITLE
MITx Residential upgrade to Quince

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#1804]
# Description/Context

The residential MITx platform upgrade is scheduled for December ___. To support that we will need to upgrade our CI environment to Quince once the release branches are created on October 10th.

# Plan/Design

- [ ] Upgrade residential MITx CI to Quince following the instructions [here](https://github.com/mitodl/ol-infrastructure/blob/main/docs/how_to/openedx/release_upgrades.md)
- [ ] Address any bugs that are identified during testing

**Comment by feoh** [comment]
Seems like this is done. Feel free to re-open and signpost with any additional work that's needed if I'm wrong.
