### ISSUE TITLE
Keycloak - Email and password registration process flow

### ISSUE THREAD

**Issue by collinpreston** [mitodl/ol-infrastructure#1818]
# Description/Context
The Keycloak process flow for email and password registration should match the flow here: https://docs.google.com/document/d/17tJ-C2EwWoSpJWZKjuhMVgsqGtyPH0IN9KakXvSKU0M/edit#heading=h.qbu1cu7zczd2

# Plan/Design
https://docs.google.com/document/d/17tJ-C2EwWoSpJWZKjuhMVgsqGtyPH0IN9KakXvSKU0M/edit#heading=h.qbu1cu7zczd2

**Comment by collinpreston** [comment]
Blocked by https://github.com/mitodl/ol-infrastructure/issues/1883.

**Comment by collinpreston** [comment]
Should also be done after https://github.com/mitodl/ol-keycloak/pull/1 is merged.

**Comment by collinpreston** [comment]
Blocked by https://github.com/mitodl/ol-infrastructure/issues/1883

**Comment by pdpinch** [comment]
@collinpreston @rhysyngsun can this be closed?

**Comment by rhysyngsun** [comment]
Yeah, we've met the functional requirements here.
