### ISSUE TITLE
Keycloak - reCAPTCHA key and secret required

### ISSUE THREAD

**Issue by collinpreston** [mitodl/ol-infrastructure#1883]
# Description/Context
In order to complete the work in https://github.com/mitodl/ol-infrastructure/issues/1818, a reCAPTCHA account will need to be created.  The key and secret associated with the reCAPTCHA account will need to be provided to the developer working 1818.

**Comment by shaidar** [comment]
Wrote the pulumi code to create a registration flow however when testing on CI, ran into the following two issues:
- It wasn't populating the recaptcha site and secret keys regardless of how I tried to pass those. Looked through the export and some of the code so make sure I'm using the right key names and that appears to be the case. So will need to spend more time troubleshooting this.
- The flow is being creating, however when running it, it throws an error about an invalid identity provider. When I compare the pulumi code to a partial export, there's an authentication execution bit that has a `registration-page-form` id, however when I try using that in pulumi it throws an error about that not being a valid authenticator. The pulumi-keycloak provider relies on the provider output from one of the keycloak API outputs. Will need to spend time messing with the API to see if it's an issue with the pulumi-keycloak library missing something or we're dealing with something else.

**Comment by shaidar** [comment]
The terraform keycloak library that pulumi relies on uses several keycloak admin API endpoints to obtain a list of valid authentication. Opened an [issue](https://github.com/mrparkers/terraform-provider-keycloak/issues/896). Looking into using [this](https://github.com/adorsys/keycloak-config-cli) as a potential answer to manage some keycloak configs through export/import.

**Comment by blarghmatey** [comment]
@shaidar is this issue still blocked, or have we developed a workaround for now?

**Comment by shaidar** [comment]
It's still blocked as there doesn't appear to be much activity on that terraform library. Given that it's just a one time config, we're handling it manually and have the pulumi code in place commented out until it gets resolved. Not ideal, but does the trick.

**Comment by collinpreston** [comment]
Closing this, thank you @shaidar
