### ISSUE TITLE
Add triggers to ocw_site concourse job to trigger on changes in `ocw-hugo-themes`

### ISSUE THREAD

**Issue by pt2302** [mitodl/ol-infrastructure#1890]
# Description/Context
When the 404 page in `ocw-hugo-themes` is changed, the concourse job should trigger to update the Fastly 404 config.

# Related Issues
https://github.com/mitodl/ocw-hugo-themes/issues/1273 and https://github.com/mitodl/ol-infrastructure/issues/1889 should be resolved first.

**Comment by blarghmatey** [comment]
This is complete now.
