### ISSUE TITLE
Production DNS configuration for MIT Open

### ISSUE THREAD

**Issue by collinpreston** [mitodl/ol-infrastructure#1896]
# Description/Context
Currently the Production instance MIT Open is accessible at https://mitopen-production-43cd80cb7414.herokuapp.com/.  This Heroku instance should have a DNS configuration to make it more easily accessible.

**Comment by shaidar** [comment]
Do we have a name for it? Are we planning on going with mitopen.mit.edu or do we plan on going with open.mit.edu and thus having to figure out what to do with the existing app using that hostname?

**Comment by Ferdi** [comment]
The final name/branding is not decided yet.  I think going with mitopen.mit.edu seems a good option for now.

**Comment by shaidar** [comment]
Since this is a temp option for now, I just added a CNAME to Route 53 and the app should now be reachable at https://mitopen.odl.mit.edu
