### ISSUE TITLE
Keycloak deployed to Production environment

### ISSUE THREAD

**Issue by collinpreston** [mitodl/ol-infrastructure#1901]
# Description/Context
In order to support SSO with MIT Open in the Production environment, we need Keycloak to also be deployed to the Production environment.

**Comment by shaidar** [comment]
New Keycloak production instances in place along with the deployed configs. Working on updating Touchstone IDP config (not necessary, but just more consistent) to use the updated SSO hostname.

**Comment by shaidar** [comment]
Touchstone IDP has been updated and I tested the login flow with it which appears to be functional.
