### ISSUE TITLE
populate additional_waffle_flags for QA and Production edxapp environments

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#1935]
# Description/Context
With the move to dockerized edxapp, we added functionality to set and maintain waffle flag configurations automatically but we never completed the configuration for doing so in any environments higher than QA. Complete that work.

# Plan/Design
see: https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/edxapp/Pulumi.applications.edxapp.xpro.CI.yaml#L7-L17

Ensure that the default flags are correct and still applicable in each environment as well.

**Comment by pdpinch** [comment]
So, every time we want to make a permanent change to a waffle flag, we should open an issue to have it added it to these Pulumi files?
