### ISSUE TITLE
Increase memory / instance size of MITx ElasticSearch clusters

### ISSUE THREAD

**Issue by feoh** [mitodl/ol-infrastructure#2003]
# Description/Context

Got paged by [this](https://opsg.in/a/i/mitodl/294eddd6-0725-490e-a9cd-13b9b0d27afa-1702916237260) alert saying that MITx elasticsearch was running out of memory.

# Plan/Design

Probably need to choose a larger instance size with more memory for this RDIS cluster.

**Comment by Ardiea** [comment]
Prob sometime this week before break would be good. But doesn't need to be right this minute. 

![image](https://github.com/mitodl/ol-infrastructure/assets/41908054/6ad047a3-afb6-4a28-8583-e27c63e9dcf5)
