### ISSUE TITLE
Tika version hard-coded

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#2033]
## Expected Behavior
Actually use the tika version information from the pipeline triggers/resources when building a new tika image. 

## Current Behavior
The tika pipeline is configured to build a new version of the AMI when a new Tika container is release by apache foundation: https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_concourse/pipelines/infrastructure/tika/packer_pulumi_pipeline.py#L11-L14

However that version information is never sent to / utilized by the packer build step when making the AMI and setting up `.env` or `docker-compose.yaml`. The version of the tika container is hard coded here: https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/tika/files/docker-compose.yaml#L22

## Possible Solution

It should be similar to edxapp where we pass an env var through the pipelines to the py infra code for `DOCKER_IMAGE_DIGEST` and `DOCKER_IMAGE_NAME` but maybe don't need to split it up and we would use the tag rather than the digest.

**Comment by feoh** [comment]
Are there any developer / user ramifications to this?

Like, I get the impression that some semantics can change between Tika versions.

**Comment by Ardiea** [comment]
I think maybe between major versions, yes? But I think within a major version there shouldn't be ramifications.
