### ISSUE TITLE
Use Keycloak as a CAS IDP

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-infrastructure#2139]
### Description/Context

Ike has a service that requires the use of a CAS IDP. The idea is to setup a dedicated Keycloak realm for that and enable the Keycloak [CAS plugin](https://github.com/jacekkow/keycloak-protocol-cas).

**Comment by shaidar** [comment]
We added the CAS plugin as part of the Keycloak build and verified that it is being installed properly. The next step was to test and verify it'll work with a CAS SP. To simulate that, we worked on using [Apache APISIX cas-auth plugin](https://apisix.apache.org/docs/apisix/plugins/cas-auth/).
- Created a realm in keycloak
- Setup an EC2 instance with a hostname through Route53
- Configured a (cas) client in Keycloak with the appropriate URLs pointing to the EC2 instance
- Went through APISIX documentation and verified that initial config is working
- Followed the [steps](https://apisix.apache.org/docs/apisix/plugins/cas-auth/) to enable a CAS route

Making a request to that route constantly threw a `Client not found` error on the Keycloak side. Tried a slew of different things on the Keycloak client side and on the APISIX side with no luck. 

Additionally, loading the URL directly (`https://<sso_hostname>/realms/<realm_name>/protocol/cas`) throws a `An internal server error has occurred`. However, nothing is mentioned in the Keycloak logs.

**Comment by shaidar** [comment]
The missing piece to resolve this issue ended up being adding the URL schema for the `Valid Redirect URI` in the CAS Keycloak client.

**Comment by blarghmatey** [comment]
We have gotten confirmation from the last remaining user of our legacy CAS service that they still require this functionality. We will need to compile some documentation about how to integrate with this CAS service and ensure that the associated realm has Touchstone configured.

**Comment by shaidar** [comment]
Once we've confirmed the realm name to be used for this, I can go ahead and start working on it.

**Comment by shaidar** [comment]
Setup realm and requested it to be registered as an SP with the IDP. Additionally, emailed needed info to Tobias.
