### ISSUE TITLE
Add keycloak to Pingdom monitoring rules

### ISSUE THREAD

**Issue by feoh** [mitodl/ol-infrastructure#2287]
### Description/Context
Pingdom is our new production SSO solution. Given how pervasive it will become, having monitoring to ensure it's up is critical.

### Plan/Design
Add pingdom uptime check rules for Keycloak production.

**Comment by shaidar** [comment]
Added Pingdom checks for QA and Prod for the Open and Data realms

**Comment by shaidar** [comment]
Apart from the basic Pingdom checks, now that we have a few apps integrated with Keycloak auth, we should also add checks for that.

**Comment by shaidar** [comment]
Added the following pingdom checks for QA and Production envs:
- Superset - setup a local keycloak account and created a synthetic check that go through the login flow to ensure that things are working.
- Open - setup a local keycloak account and created a synthetic check that go through the login flow to ensure that things are working. Also created a check that clicks on `Touchstone`  and verifies returned URL. 

Closing this issue now as it should cover the checks for now and we can create another issue if needed.
