### ISSUE TITLE
Notifications when a container stops running

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-infrastructure#2324]
### Description/Context

We need to be notified if/when a running docker container stops. Currently in cases where we have load balanced instances, if a container fronted by traefik dies, we don't seem to get any alerts/notifications about it.

**Comment by Ardiea** [comment]
Relates to https://github.com/mitodl/ol-infrastructure/issues/1426

**Comment by blarghmatey** [comment]
Closing as a duplicate of https://github.com/mitodl/ol-infrastructure/issues/1426
