### ISSUE TITLE
Instances with expired credentials

### ISSUE THREAD

**Issue by shaidar** [mitodl/ol-infrastructure#2370]
Seeing instances with expired credentials whereby we're having to manually trigger an instance refresh to replace those instances with new one that have fresh credentials.
### Expected Behavior

Ideally, credentials should be automatically renewed prior to them expiring.

### Additional Details

This is in reference to this [alert](https://mitodl.slack.com/archives/GBDLJJX51/p1713793472270529)

**Comment by feoh** [comment]
This seems important.
