### ISSUE TITLE
"*.odl.mit.edu" is set to expire on 2024-07-03 at 11:59 PM UTC.

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#2490]
Hi Michael Davidson,

Your TLS certificate "*.odl.mit.edu" is set to expire on 2024-07-03 at 11:59 PM UTC.

To avoid service disruptions, we recommend you replace this certificate now.

View and update your expiring certificate via the UI: https://manage.fastly.com/network/certificates/MARdKnUyUZSrJA27gLeZs5

Cheers,
The Fastly Team
[support@fastly.com](mailto:support@fastly.com)

**Comment by Ardiea** [comment]
FYI

Can we change the contact email on this account to something that makes more sense and has more visibility than [ocw-ops](https://groups.mit.edu/webmoira/list/ocw-ops)? 

- @pdpinch

**Comment by pdpinch** [comment]
Yes please. 

I don't think I have the credentials to make that change myself, but I am strongly in favor of it.

**Comment by Ardiea** [comment]
Finally got this email address changed. Verified the login still works.
