### ISSUE TITLE
Custom concourse resource for syncing between S3 buckets

### ISSUE THREAD

**Issue by mbertrand** [mitodl/ol-infrastructure#250]
It would be nice to have a concourse resource similar to `concourse-rclone-resource` that can sync from one remote S3 bucket to another (the current implementation only syncs from remote to local, or local to remote).

**Comment by mbertrand** [comment]
Currently using `aws s3 sync` CLI commands in the pipeline instead (the `copy-s3-buckets` task).

**Comment by mschuchard** [comment]
@blarghmatey #559

**Comment by blarghmatey** [comment]
Thanks for the reminder. Applied to RC and will validate there. Assuming all works fine we will promote it to production.
