### ISSUE TITLE
Refactor edX asset compilation to remove Paver references

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#2504]
### Description/Context

The Paver utility has been deprecated in edX projects. The asset compilation has already been rewritten to not rely on Paver. We still use Paver in the build of our edX images and need to remove them. Currently they generate warning messages during the build step.

### Plan/Design

- [ ] Refactor the edX Earthfile and Dockerfile definitions to follow the deprecation warnings
  - [ ] https://github.com/openedx/edx-platform/pull/34318/files#diff-8e4387cbbe877b0d2638a138b05ad2d3ecc0b4e3665658612f04601df20cf3ceR172-R181
  - [ ] https://github.com/openedx/edx-platform/pull/34318/files#diff-8e4387cbbe877b0d2638a138b05ad2d3ecc0b4e3665658612f04601df20cf3ceR212-R218

**Comment by Ardiea** [comment]
https://github.com/overhangio/tutor/blob/ff0f626e136339b9236cf00c1a2a67563a347f2b/CHANGELOG.md?plain=1#L41-L58
