### ISSUE TITLE
Fastly CDN for NextJS Learn

### ISSUE THREAD

**Issue by feoh** [mitodl/ol-infrastructure#2711]
### Description/Context

- [ ] Re-use current fastly code for mainline learn to create a new Fastly CDN distribution for nextjs-rc.learn.mit.edu
- [ ] Adjust Heroku footprint for learn RC to exactly match learn production for performance testing. @ChristopherChudzicki and/or @jonkafton will inform devops when perf testing concludes so we can downsize accordingly.

**Comment by ChristopherChudzicki** [comment]
Things I know we want:
- cache key should include query parameters ... all different:
    - http://localhost:8062/search?certification_type=professional&resource=123
    - http://localhost:8062/search?certification_type=professional&resource=456
    - http://localhost:8062/search?certification_type=professional
    - http://localhost:8062/search 
- `Content-Type: text/x-component` should be cached... It's used for nextjs's RSC requests
