### ISSUE TITLE
mitxonline: add logo URLs to MFE environment variables

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#279]
mitxonline logos and favicon are not rendering on lms-qa.

Setting the following env variables should fix it:

from https://github.com/edx/frontend-app-learning/blob/a003059c8f70fc8371d0ef22a83b0bad2ca23f4f/.env#L15-L18

LOGO_URL=''
LOGO_TRADEMARK_URL=''
LOGO_WHITE_URL=''
FAVICON_URL=''

**Comment by blarghmatey** [comment]
What are the values that shoudl be used for those parameters?

**Comment by pdpinch** [comment]
`LOGO_URL` should be coming from the mitxonline theme, and I expect it be at /static/mitxonline-theme/images/logo.png. You can see it at https://github.com/mitodl/mitxonline-theme/blob/main/lms/static/images/logo.png

We can use the same logo for `LOGO_TRADEMARK_URL`. I believe it appears in the footer. 

I haven't been able to find where `LOGO_WHITE_URL` is used, but I'll add one to the theme. 

We have been using the same FAVICON_URL everywhere and it's in the theme at /static/mitxoneline-theme/images/favicon.ico

**Comment by blarghmatey** [comment]
Thanks, we'll get that updated. :+1:

**Comment by shaidar** [comment]
@pdpinch This should be in place now
