### ISSUE TITLE
Implement AWS ECR as a pull-through cache

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#2801]
### Description/Context

We are hitting Docker Hub rate limits on pulling images to our EC2 environment. This causes instances to get stuck in a launch/fail loop that further exacerbates the rate limit errors. We need to implement ECR as a pull-through image cache that we then rely on for all of our image pulls in our AWS environments.

### Plan/Design

- [ ] Create an ECR repository
- [ ] Configure docker hub pull-through policy for ECR
- [ ] Migrate docker-compose instances to pull from ECR
- [ ] Migrate EKS to pull from ECR

### Notes
This blog post may be helpful in determining how to implement the appropriate configuration https://marcincuber.medium.com/implementing-aws-ecr-pull-through-cache-for-eks-cluster-most-in-depth-implementation-details-e51395568034

**Comment by feoh** [comment]
@blarghmatey already did this. Closing.
