### ISSUE TITLE
Deploy and enable edx-notes API

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#284]
Notes api can be turned on by:
1) Setting `settings.FEATURES["ENABLE_EDXNOTES"]=True` through environment yml files in LMS.
2) Setting `Enable Student Notes` to `true` in `Advanced Settings` of the specific course in Studio.
3) In case we are going to run notes service on different server / ip, we might have to change the environment variables mentioned [here](https://github.com/edx/edx-platform/blob/master/lms/envs/common.py#L1906) as well.

Notes feature is dependent on `edx-notes-api`, `MySQL` and `elasticsearch` to work properly. Although we can disable the usage of elasticsearch by setting `settings.ES_DISABLED=True` in `edx-notes-api` environment. We can use the `MAX_NOTES_PER_COURSE` variable in the `edx-notes-api` environment to limit notes creation as well.

_Originally posted by @HamzaIbnFarooq in https://github.com/mitodl/edx-platform/issues/268#issuecomment-878962826_

**Comment by blarghmatey** [comment]
This is related to #531

**Comment by pdpinch** [comment]
The user-accessible setting in studio may have a dependency on the course-authoring MFE. (i.e. the setting may have moved from advanced settings into a UI that's only available via the MFE)
