### ISSUE TITLE
Add PR and issue templates to repo

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#292]
I think it would help me understand that PRs and the issues in this repo if they followed a more consistent format.

**Comment by blarghmatey** [comment]
What are the questions you want to be able to answer/specific information you are looking for when looking at issues and PRs? That will help to determine what to put in the templates.

**Comment by pdpinch** [comment]
Just the basics would be an improvement:

#### What are the relevant tickets?
(Required)

#### What's this PR do?
(Required)

#### How should this be manually tested?
(Required)

#### Where should the reviewer start?
(Optional)

#### Any background context you want to provide?
(Optional)

**Comment by blarghmatey** [comment]
I added a [PR template](https://github.com/mitodl/ol-infrastructure/blob/main/.github/pull_request_template.md) to this repo a couple weeks ago. I was going to add issue templates as well this week.
