### ISSUE TITLE
enable bulk email - flag

### ISSUE THREAD

**Issue by briangrossman** [mitodl/ol-infrastructure#295]
To enable bulk email, you need to set a flag in Django: `/admin/bulk_email/bulkemailflag/`

Note that the settings should be:
- Bulk Email Flag Enabled: `true`
- Require course email authorization: `false`

![image](https://user-images.githubusercontent.com/21342568/128209262-a2661580-ebbc-4266-bc95-7c70b70ffcd1.png)

Some details [here](https://github.com/edx/edx-platform/blob/3e3c83629b84a6e099db00088ece30a60ccb69d0/lms/djangoapps/bulk_email/models.py#L464)

**Comment by blarghmatey** [comment]
This has been applied in production
