### ISSUE TITLE
enable VideoUploadsEnabledByDefault flag

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#297]
To enable the video uploads item in the Content menu in edx Studio, you need to set a flag in Django: /admin/video_pipeline/videouploadsenabledbydefault/

Note that the settings should be:

    Enabled: true
    Enabled for all courses: true

<img width="427" alt="image" src="https://user-images.githubusercontent.com/430126/128386927-ed7d0db3-6aa3-4254-8924-fd23ef1eeb6a.png">

(similar to #295)

**Comment by pdpinch** [comment]
I also created a flag for HLSPlaybackEnabledFlag, but it's not clear to me what impact that had.

**Comment by pdpinch** [comment]
I also had to enabled CourseYouTubeBlockedFlag for each course on the site

**Comment by blarghmatey** [comment]
Looks like these flags are set in production now. I haven't added the HLS flag until we decide that it's necessary. I'll keep this issue open for now in case we need to come back to it.

**Comment by pdpinch** [comment]
Both flags were required on Residential, in order to playback hls videos imported from mitxonline. 

1. `/admin/video_pipeline/videouploadsenabledbydefault/`
2. `admin/video_pipeline/HLSPlaybackEnabledFlag/`
