### ISSUE TITLE
set BULK_EMAIL_DEFAULT_FROM_EMAIL 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#327]
Should be set to the support email address for MITx Online.

In xPRO, this is set like so:
```
      BULK_EMAIL_DEFAULT_FROM_EMAIL: {{ support_email }}
```

**Comment by blarghmatey** [comment]
What is the value that should be used here? It can be set at https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/images/edxapp/templates/common_values.yml#L136

**Comment by pdpinch** [comment]
mitxonline-support@mit.edu 

Setting this will also fix https://github.com/mitodl/mitxonline/issues/115

**Comment by pdpinch** [comment]
Scratch that. It looks like the setting now is `DEFAULT_FROM_EMAIL` (it's not annotated, so it doesn't show up in the documentation) 

`DEFAULT_FROM_EMAIL` = mitxonline-support@mit.edu
`EMAIL_USE_DEFAULT_FROM_FOR_BULK` = true

**Comment by shaidar** [comment]
I'm assuming this will also need the [following keys/values](https://github.com/mitodl/salt-ops/blob/19e29e63e9fad9bc84ec18d8d8297b7a19d98b9a/pillar/edx/ansible_vars/cloud_deployment.sls#L213-L216) added
