### ISSUE TITLE
 Add Google Analytics (GA) tag for courses.mitxonline.mit.edu (prod)

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#380]
As a admin or a marketing person, I'd like to know how often people are visiting the mitxonline courseware.

open edX currently only supports `UA-` style GA tags, not the `G-` style G4 tags. 

### acceptance criteria

- [x] Add the tag `UA-5145472-48` to the production deployment of courses.mitxonline.mit.edu

**Comment by blarghmatey** [comment]
This is deployed in production now.
