### ISSUE TITLE
mitxonline waffle flags and settings

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#384]
This is an issue for collecting a list of waffle flags and settings. Most, if not all, of these have been set on qa and production instances. We are building this list to keep track of them when it comes time to build any new servers. 

- [ ] `completion.enable_completion_tracking setting` for "resume course" and for green check marks. 
  - [ ] CI
  - [x] [RC](https://courses-qa.mitxonline.mit.edu/admin/waffle/switch/3/change/)
  - [x] production
- [ ] `videos.video_image_upload_enabled` allows users to upload video thumbnails, which cannot be exported and imported
  - [ ] CI
  - [x] [RC](https://courses-qa.mitxonline.mit.edu/admin/waffle/switch/2/change/)
  - [ ] production
- [ ] `grades.assume_zero_grade_if_absent` "This is for the frontend-app-gradebook MFE"
  - [ ] CI
  - [x] [RC](https://courses-qa.mitxonline.mit.edu/admin/waffle/switch/1/change/)
  - [ ] production
- [ ] `course_experience.relative_dates`
   - set per course run: `force_on`
- [ ] embargoes
  - [x] [RC test course](https://courses-qa.mitxonline.mit.edu/admin/embargo/restrictedcourse/)
  - [x] [production: six courses x 3 countries]

**Comment by blarghmatey** [comment]
@pdpinch is this ready to close? Or do we need to keep this open for tracking purposes?
