### ISSUE TITLE
Maple: release residential SGA pin after correct version is pinned upstream

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#456]
After we fix https://github.com/mitodl/edx-platform/issues/276 I think we should remove the explicit pins here:

https://github.com/mitodl/ol-infrastructure/blob/91b5cf04e7ff8824348ae930b657e1b85e65005a/src/bilder/images/edxapp/group_data/all.py#L44

and here:

https://github.com/mitodl/ol-infrastructure/blob/91b5cf04e7ff8824348ae930b657e1b85e65005a/src/bilder/images/edxapp/group_data/all.py#L54

**Comment by blarghmatey** [comment]
Removed the installation of edx-sga as a separate step in our build customization layer.
