### ISSUE TITLE
Maple: update or remove edx-username-changer pin

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#457]
We'd like to pick up the bug fix in v0.3.0 of edx-username-changer

https://github.com/mitodl/ol-infrastructure/blob/91b5cf04e7ff8824348ae930b657e1b85e65005a/src/bilder/images/edxapp/group_data/all.py#L25

https://github.com/mitodl/ol-infrastructure/blob/91b5cf04e7ff8824348ae930b657e1b85e65005a/src/bilder/images/edxapp/group_data/all.py#L35

**Comment by blarghmatey** [comment]
This is currently set to 0.3.0
