### ISSUE TITLE
Restructure concourse pulumi code to allow different classes of concourse workers with different tags / teams.

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#468]
The OCW studio application relies on Concourse for managing all of the content publishing. As a result this can cause a swarm of jobs in the Concourse cluster which starves other pipelines for resources. In order to segregate the workload and keep the rest of our build environments cleaner we want to deploy a dedicated installation of Concourse to be used for OCW content publishing. This will also allow us to place it on a subdomain of ocw.mit.edu (maybe build.ocw.mit.edu) to make it more a part of the overall content creation experience.

In order to support a separate installation there are a few refactorings of the Concourse project in Pulumi that will be needed. First, we will want to expand the namespace of the stack definitions from `applications.concourse.<ENVIRONMENT_STAGE>` (e.g. QA, Production) to `applications.concourse.<ENVIRONMENT_NAME>.<ENVIRONMENT_STAGE>` (e.g. operations.QA, applications.QA, etc.). We will also need to customize the IAM policy definitions for the separate installations to allow for permissions on the appropriate resources. The majority of permissions needed for the OCW cluster will be related to S3 bucket access. The newly dedicated operations installation will need to be granted expanded permissions to allow for tasks such as building EC2 AMIs with Packer, running Pulumi projects to provision AWS infrastructure, etc.

-------------

Design a framework to allow us to arbitarily define classes of concourse workers. Each class of worker should have the ability to sepcify both concourse-teams and concourse-tags on the node. Additionally, each should support over-riding the OU **AWS** tag from 'operations' to something else for cost reporting reasons.

**Comment by Ardiea** [comment]
We could use tags/team membership on worker nodes and avoid recreating the entire concourse infrastructure just for OCW. 

https://concourse-ci.org/concourse-worker.html#worker-configuration

**Comment by blarghmatey** [comment]
Creating a dedicated worker pool is an avenue that was considered, but the magnitude of pipelines that are required for running OCW make it worth the effort of segmenting it to its own specific installation. This will allow for fine tuning of the entire installation for that workload without having to balance against other uses of the infrastructure. It will also eliminate the potential for either OCW pipelines blocking execution of other use cases, and vice versa. It will also allow us to place it under the OCW domain so that the build UI can be treated as part of the overall application/publishing environment.
