### ISSUE TITLE
OCW 404 and 3xx reporting

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#487]
After we launch the new OCW site, it will be useful to report on the top 10 404s per month (or something similar), so we can identify any pages that were missed in the migration to the new site. 

This will involve collecting and aggregating Fastly logs, and then querying and reporting on them.

**Comment by Ardiea** [comment]
Created a dashboard that can show 1hr of data in Grafana and shared the link in Slack. Will create a better report with Trino once the data is ingested there. Moving back to ready status.

**Comment by pdpinch** [comment]
Thanks @Ardiea. Interesting stuff. Can we tweak some things?

- Can we omit 304s (Not Modified)? They aren't interesting. I'm much more interested in the 301s. 
- Nitpick: 3xx responses shouldn't be described as "errors". 

Let me know if there's a better way to comment on this stuff. I don't suppose there's a PR?
