### ISSUE TITLE
fastly / varnish configuration issue with ocw-live-production

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ol-infrastructure#544]
Something seems to be off with the fastly / varnish configuration at https://ocw-live-production.global.ssl.fastly.net/.  The following URLs produce a 301 error:

https://ocw-live-production.global.ssl.fastly.net/search
https://ocw-live-production.global.ssl.fastly.net/courses/9-98-neuropharmacology-january-iap-2009 (or any course)

**Comment by shaidar** [comment]
@gumaerc Can you take a look now and close the issue if it's been fixed.
