### ISSUE TITLE
ocw-to-hugo output upload failing

### ISSUE THREAD

**Issue by gumaerc** [mitodl/ol-infrastructure#554]
The last step of the `ocw-to-hugo` pipeline is failing in QA and production with an error about the S3 bucket:

```
selected worker: ip-10-0-3-33
Uploading to S3...
fatal error: Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"
```

https://cicd.odl.mit.edu/teams/ocw/pipelines/ocw-to-hugo-production/jobs/convert-plone-to-hugo/builds/75

**Comment by blarghmatey** [comment]
This is resolved now after fixing the updates to the s3-sync resource that also enables direct syncing between buckets.
