### ISSUE TITLE
OCW legacy redirects for course pages 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#556]
In the transition from OCW legacy to OCW Next, we would like to preserve as many URLs as possible. We've considered a number of alternatives, and we've determined that redirects in Fastly are the best option. 

### acceptance criteria

0. This only applies to paths that start with `/courses/` followed by a department name. A list of department names can be found in https://github.com/mitodl/ocw-to-hugo/blob/master/src/departments.json

1. Remove the department name from all URLs. The simplest example: 
    **incoming**: `/courses/mathematics/18-06-linear-algebra-spring-2010/`
    **301 redirect to**: `/courses/18-06-linear-algebra-spring-2010/`
     
    if this fails to return a working URL, then

2. Insert /pages/ into the URL after the course id (in addition to removing the department). For example: 
    **incoming**: `/courses/mathematics/18-06-linear-algebra-spring-2010/syllabus/`
    **301 redirect to**: `/courses/18-06-linear-algebra-spring-2010/pages/syllabus/`

   if this fails to return a working URL, then 

3. replace the path after the course id with /resources/ (in addition to removing the department). For example: 
    **incoming**: `/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/lecture-2-elimination-with-matrices/`
    **301 redirect to**: `/courses/18-06-linear-algebra-spring-2010/resources/lecture-2-elimination-with-matrices/`
   
    - note that `video-lectures` was also removed in this path 

### out of scope

- redirects for paths that start with anything other than courses, like `/resources/` or `/high-school/`

**Comment by shaidar** [comment]
@pdpinch Can we have example links where (2) and (3) apply? Just trying to test/verify Fastly config and need examples.

**Comment by pdpinch** [comment]
That's really just an example, although it's a common one. 

If the request was for `/courses/mathematics/18-06-linear-algebra-spring-2010/video-lectures/lecture-2-elimination-with-matrices/` I would have expected it to be rewritten in step 2 to `/courses/18-06-linear-algebra-spring-2010/pages/video-lectures/lecture-2-elimination-with-matrices/` which should return a 404.

**Comment by pdpinch** [comment]
@shaidar  can we at least deploy a fastly config for rules 0, 1 and 2 so we can see how well that works?

**Comment by shaidar** [comment]
@pdpinch Think all conditions should be working now on the test Fastly distro - https://ol-devops-ci.odl.mit.edu
