### ISSUE TITLE
Better cookies names for staging.mitx.mit.edu

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#568]
We are seeing cookie overwriting issues between lms.mitx.mit.edu and staging.mitx.mit.edu which manifests as the MFE getting an error loading courseware. 

Video with issue can be found in ticket https://odl.zendesk.com/agent/tickets/114325

**Comment by pdpinch** [comment]
Looking at my cookies in firefox, I think we should consider changing the names of some or all of the highlighted cookies: 

<img width="1604" alt="Screen Shot 2022-01-20 at 2 01 52 PM" src="https://user-images.githubusercontent.com/430126/150407075-13b531e5-b4f7-47ea-8e81-925e8f68e519.png">

**Comment by blarghmatey** [comment]
This will be addressed via https://github.com/mitodl/ol-infrastructure/pull/569
