### ISSUE TITLE
Alert on edX task queues not draining

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#590]
We need to know when the edX workers aren't processing tasks. The Celery process is using Redis elasticache for the task queue, so we should be able to export a metric to Cloudwatch that we can alert on when it's not draining.

**Comment by Ardiea** [comment]
The way forward would be to install a small standalone machine or ECS container that runs the redis_exporter and connects to the elasticache instances. It would then expose the metrics to vector which can ship it to -> grafana.

**Comment by blarghmatey** [comment]
@Ardiea do you think that we could write a reasonable alert for this using your Cloudwatch alarms? From looking into situations previously it seemed like `CurrItems` correlated well with the overall queue length. Namely, when that value climbed but didn't drop back down over a given period (e.g. 1 - 2 hours) then it signified that we were getting behind in task queue processing.

**Comment by Ardiea** [comment]
I think there is too much other stuff going on with redis to be able to do anything meaningful with CurrItems. Looking at residential-prod for the past 30 days, it has been up and down between 970,000 and 911,000 with no real pattern. I don't think we could make an inference about the task queue with generalized data like that. We would need to know the size of specific keys / dbs within the cluster.

**Comment by blarghmatey** [comment]
This is superseded by https://github.com/mitodl/ol-infrastructure/issues/1609
