### ISSUE TITLE
OCW: redirect terms page

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#623]
something like:

301 /terms/  /pages/privacy-and-terms-of-use/
301 /terms/index.htm /pages/privacy-and-terms-of-use/

**Comment by shaidar** [comment]
This should be working now and can be tested [here](https://ol-devops-ci.odl.mit.edu)

**Comment by shaidar** [comment]
This has been deployed to all envs and closing for now.
