### ISSUE TITLE
OCW: redirect  legacy fair use page

### ISSUE THREAD

**Issue by noisecapella** [mitodl/ol-infrastructure#624]
I noticed that some links in the legacy site go to https://ocw.mit.edu/help/faq-fair-use/. Our code will change this to `/help/faq-fair-use` but that doesn't exist. We should create a page or otherwise figure out how to direct these links

The old fair use page is being replaced by a help center article, at https://mitocw.zendesk.com/hc/en-us/sections/4414782875163-FAIR-USE

Until we get a chance to replace the URLs in the legacy content, we should set up a redirect from `/help/faq-fair-user` to https://mitocw.zendesk.com/hc/en-us/sections/4414782875163-FAIR-USE

**Comment by shaidar** [comment]
@pdpinch This is now deployed [here](https://ol-devops-ci.odl.mit.edu) and should be ready for testing

**Comment by shaidar** [comment]
Added/Fixed

**Comment by pdpinch** [comment]
Confirmed:

- [x] https://ol-devops-ci.odl.mit.edu/help/faq-fair-use
- [x] https://ol-devops-ci.odl.mit.edu/help/faq-fair-use/
- [x] https://ol-devops-ci.odl.mit.edu/help/faq-fair-use/index.htm 

please deploy ocwnextgen.odl.mit.edu and also to the production site when it launches.

**Comment by shaidar** [comment]
This has been deployed to all envs and closing for now.
