### ISSUE TITLE
Update vector host metric collection to use builtin filesystem filtering, etc

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#631]
Vector includes a mechanism to filter in / out filesystems and devices. We should utilize this instead of the VRL that I wrote that does the same thing. It is cleaner and easier to understand. 

https://vector.dev/docs/reference/configuration/sources/host_metrics/

**Comment by Ardiea** [comment]
> Is this done now? I know you had added some disk filtering in a recent PR.

No, I haven't done it universally. Just in that one thing I was working with that day. I still need to deploy it every with with salt-stack code and also update the pyinfra version of the same thing.

**Comment by blarghmatey** [comment]
@Ardiea ignoring Salt controlled hosts, is there any other work to do on this?

**Comment by Ardiea** [comment]
All set 

https://github.com/mitodl/ol-infrastructure/blob/main/src/bilder/components/vector/templates/host_metrics.yaml#L14-L17
