### ISSUE TITLE
Scale down OCW concourse workers, all environments

### ISSUE THREAD

**Issue by Ardiea** [mitodl/ol-infrastructure#636]
Scale down OCW concourse workers, all environments

Just five workers from now on in QA and Prod

**Comment by pdpinch** [comment]
Can you say something about how you determined this to be the right number (at least for now) ?

**Comment by Ardiea** [comment]
> Can you say something about how you determined this to be the right number (at least for now) ?

Yeah! So, previously we had 200-500 containers per ocw worker and maybe like 1000 volumes per worker (so, like 15000-20000, a lot...). Since https://github.com/mitodl/ocw-studio/pull/982 was merged, we're down to 2-10 active containers per ocw worker and <400 volumes total. That PR seems to have been the game changer that concourse needed to reach stability. 

Honestly, I think we could do 2 OCW workers and be fine, but I don't want any surprises if something should happen that causes a bunch of those individual course jobs to fire off. Though my understanding now is that such an occurrence is unlikely.
