### ISSUE TITLE
Retire AMPS redirect server in favor of Fastly redirects

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#664]
We are currently running an (aging) Nginx server on EC2 that's entire purpose in life is to serve a set of redirect routes. This was done to allow for use on domains that required an A record due to their being an apex record in the given domain. Now that we have adopted Fastly we have the ability to use their anycast IP to fulfill that requirement. As such we should look at re-creating the redirect rules in the following files as rules in one or many Fastly distributions so that we have no server maintenance required to keep this running.

https://github.com/mitodl/salt-ops/blob/main/pillar/nginx/amps_redirect.sls
https://github.com/mitodl/salt-ops/blob/main/pillar/nginx/chalkradio_redirect.sls
https://github.com/mitodl/salt-ops/blob/main/pillar/nginx/mitxpro_redirect.sls

**Comment by shaidar** [comment]
We started looking into the possibility of not worrying about the video redirects and potentially retiring those, however in looking at the NGINX logs on the redirect instance, it appears that some of the traffic is referred by `starcellbio`. So, even if video folks were fine with not having any redirects, we'd have problems with folks using the `startcellbio` app.

**Comment by shaidar** [comment]
Completed work on moving the config for `amps_redirect` into Fastly. For `chalkradio` we are looking at handling it using Route53 following instructions [here](https://help.simplecast.com/en/articles/2717207-how-to-setup-a-custom-domain)

**Comment by shaidar** [comment]
Ended up going with Fastly for the chalkradio redirects as the simplecast instructions only allow to specify one custom domain and we have `.net`, `.com`, and `.org` to redirect.

**Comment by shaidar** [comment]
This is currently on-hold with a ticket open with Fastly as we currently can't add the `mitxpro.mit.edu` domain in Fastly given the already seen error message:
```Domain 'mit.edu' is already taken by another customer```

**Comment by shaidar** [comment]
All configs are now in place and tested on a Fastly distribution. Turned off EC2 instance for now and will give it a week or so to terminate it and put in a PR to remove the salt code

**Comment by blarghmatey** [comment]
@shaidar looks like this is ready to be closed after you terminate and delete the server from Salt :smile:

**Comment by shaidar** [comment]
Instance terminated
