### ISSUE TITLE
Disaster recovery for site-wide errors

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#688]
We need to have infrastructure and runbooks in place to allow us to rapidly recover from site-wide user-facing errors on the live OCW site. This will typically occur in the context of a mass-publish event.

To recover from this situation we need a known-good copy of the content prior to the event that generated the bad state. To this end we will:
- [x] Create a backup bucket in S3
- [X] ~Modify the mass publish Concourse pipeline to execute an S3 sync from the active live bucket to the standby backup bucket~ Write standalone cron-ish jobs that will do this backup once a day. 
  - [ ] ~In the event that the S3 sync fails then the whole pipeline will fail~
- [x] #811
- [ ] Create a script/Concourse pipeline/other that will add a bucket policy to the backup bucket that disallows writing new content to the bucket

Notes:
- If a bad build of a course is published prior to a mass publish then that bad course build will be present in the backup content. This is an acceptable risk.
- Open questions:
  - What is the threshold for determining that the site is sufficiently broken to engage the break glass scenario?
  - What is the testing strategy to prevent break-glass situations?
  - Who is responsible for making a determination of when to break-glass?
  - Are there any other situations/workflows besides mass publish that could lead to a break-glass situation?

**Comment by Ardiea** [comment]
Partially addressed with PR 691

**Comment by pdpinch** [comment]
@blarghmatey do you think we can close this?

**Comment by blarghmatey** [comment]
Yeah, as long as we're okay with recovery being manual then I don't think there's much else that needs to be done here.
