### ISSUE TITLE
OCW URLs return "The page isn’t redirecting properly" instead of 404

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#715]
In some cases, when we expect a 404 response we are getting (in Firefox):

> The page isn’t redirecting properly
> 
> An error occurred during a connection to ocwnext.odl.mit.edu.
> 
>     This problem can sometimes be caused by disabling or refusing to accept cookies.

We are planning to fix these URLs, but it's still unexpected and confusing that they don't return 404. 

Some examples:

1. https://ocwnext.odl.mit.edu/courses/18-100c-real-analysis-fall-2012/pages/index.htm (link [18.100C Real Analysis](https://ocwnext.odl.mit.edu/courses/18-100c-real-analysis-fall-2012/pages/index.htm) on https://ocwnext.odl.mit.edu/courses/18-s997-high-dimensional-statistics-spring-2015/pages/syllabus/ )
2. https://ocwnext.odl.mit.edu/courses/18-700-linear-algebra-fall-2013/pages/index.htm (link [18.700 Linear Algebra](https://ocwnext.odl.mit.edu/courses/18-700-linear-algebra-fall-2013/pages/index.htm) on https://ocwnext.odl.mit.edu/courses/18-s997-high-dimensional-statistics-spring-2015/pages/syllabus/ )

**Comment by shaidar** [comment]
@pdpinch I think I found a decent workaround to address this. Can you try it out [here](https://ol-devops-ci.odl.mit.edu/courses/18-100c-real-analysis-fall-2012/pages/index.htm) and let me know whether to go ahead and deploy across all envs

**Comment by pdpinch** [comment]
This is working in production now.
