### ISSUE TITLE
OCW: block search engines from crawling ocw.mit.edu/ans7870/

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#739]
The HTML pages hosted on ans7870 have not been updated in years. Many of them cause Google's search engine crawler to throw errors, decreasing the mobile score for the site. 

For now, while we don't understand what content is in this tree, we should block it from being indexed. Perhaps after we review it, remove archived material and update HTML for the modern era, we will allow the search engines to index it again.

**Comment by blarghmatey** [comment]
By "update the HTML" I'm hoping you mean _not_ in the ans7870 route...
