### ISSUE TITLE
OCW: redirect /high-school/* to ZenDesk help page 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#771]
The OCW "highlights for high school" was abandoned in next gen, but people are still looking for it. To avoid lost of customer support issues, we'd like to direct them to a page explaining the decision. Eventually, a few of the courses will be ported to nextgen, although as regular courses. 

The OCW team attempted to add a redirect through fastly, but it seems like they are limited to one-to-one redirects. No wild cards. 

They'd like to redirect everything that starts with the path `/high-school/` to go to https://mitocw.zendesk.com/hc/en-us/articles/5332864282907

**Comment by Ardiea** [comment]
Turns out this isn't fast and easy so I will connect with @blarghmatey at some point here to do this.

**Comment by blarghmatey** [comment]
This is a good task to work on after we finish the setup to get Fastly provisioned via Pulumi for #840

**Comment by shaidar** [comment]
@pdpinch Can we have an example of a `high-school` link to test things out

**Comment by pdpinch** [comment]
Here's one. I'll add more. 

https://ocw.mit.edu/high-school/physics/chandra-astrophysics-institute/ => https://mitocw.zendesk.com/hc/en-us/articles/5332864282907

**Comment by shaidar** [comment]
@pdpinch This is now deployed on QA

**Comment by blarghmatey** [comment]
This is live on production as of yesterday
