### ISSUE TITLE
Investigate MongoDB timeouts in edx-platform communicating with MongoDB Atlas

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#784]
We are using MongoDB Atlas to host our MongoDB clusters that are powering our Open edX installations. We are using AWS VPC peering for the network connection from the edX instance to the MongoDB clusters. There seems to be something in the network topology that causes unpredictable latency spikes that result in connection timeouts and heartbeat errors. We need to investigate the reason for these latency spikes in order to understand how to remediate them.

Relevant Sentry errors are visible [here](https://sentry.io/organizations/mit-office-of-digital-learning/issues/2107134242/?project=1757731&query=is%3Aunresolved) and [here](https://sentry.io/organizations/mit-office-of-digital-learning/issues/2807869412/?project=1757731&query=is%3Aunresolved)

**Comment by Ardiea** [comment]
I did find a discrepancy.

This document says to open 27015 - 27017 inclusive from clients -> mongodb atlas while we are opening _just_ 27017.

https://www.mongodb.com/docs/atlas/security-vpc-peering/

I don't have any evidence to support this being the cause of the issue, though. 

https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/infrastructure/mongodb_atlas/__main__.py#L100-L101

**Comment by Ardiea** [comment]
https://www.mongodb.com/docs/atlas/troubleshoot-connection/#attempting-to-connect-to-a-database-deployment-from-behind-a-firewall

says we should have 27016 opened in addition to 27017 'for sharded clusters' which I believe is what we have?

**Comment by blarghmatey** [comment]
Those sound like very reasonable causes for the issues we're having (though we aren't using sharded clusters, just a replica set)
