### ISSUE TITLE
EDX App Kubernetes Migration

### ISSUE THREAD

**Issue by mitangelo** [mitodl/ol-infrastructure#786]
## Rationale ##
This Epic involves migrating the open-edx application to the kubernetes platform on AWS. We have a google doc highlighting the road map. https://docs.google.com/document/d/1hxrI02K1QG6fJ1RFoGMPpXTs4huAbznKEeRjDMRht_o/edit?pli=1#

## Stakeholder Point of Contact ##
@Ferdi @pdpinch @blarghmatey 

## Dependencies ##

- [ ] Understanding the current prod deployment for edx-platform, Specifically how it is different from the upstream vanilla 
- [ ] Understanding the architectural components of edx-platform. LMS, CMS, Celery
- [ ] Implementing the needed Dockefiles for the edx-platform 
- [ ] Implementing a Kubernetes Cluster in Dev, Staging, QA and Production where the edx-platform can be deployed. 
- [ ] Thorough understanding of the way the edx-platform application is currently monitored in production. Does the app support metrics?
- [ ] Setup Supporting infrastructure(redis, mysql, opensearch) in AWS to enable the edx-platform application to be deployed. 

## Discussion ##

There is an ongoing discussion at this location. https://github.com/mitodl/hq/discussions/12
Anyone having any question can add to that discussion. Please feel free to ask and comment on anything posted there. 

Initial Kubernetes Design Decision: https://github.com/mitodl/hq/discussions/13

## Context ##

We would like to migrate the edx-application running on vms to kubernetes. The goal is to streamline the application delivery and simplify the process via kubernetes. We would like to move away from the ansible setup that is being currently used to setup edx on vms. 

## Issues ##

- [ ] https://github.com/mitodl/ol-infrastructure/issues/789
- [ ]  https://github.com/mitodl/ol-infrastructure/issues/788
- [ ]  https://github.com/mitodl/ol-infrastructure/issues/787
- [ ] https://github.com/mitodl/ol-infrastructure/issues/790
- [ ] https://github.com/mitodl/ol-infrastructure/issues/791
- [x] https://github.com/mitodl/ol-infrastructure/issues/792
- [x] https://github.com/mitodl/ol-infrastructure/issues/801

## Acceptance criteria ##

A fully functional, highly available deployment of edx-platform along with monitoring, logging, alerting and CI/CD implemented for deployment in all environments.(Dev, Staging, Production)

## Proof ##

To Be Seen :)

**Comment by mitangelo** [comment]
https://github.com/mitodl/ol-infrastructure/issues/801 InProgress

**Comment by blarghmatey** [comment]
After some exploratory work on Kubernetes we have decided that the overall effort is not worth the investment right now given our team capacity and competing priorities. One of the blocking items is the level of effort required to make secrets actually secret while they are in use. We will monitor progress on how sensitive data is managed in K8s to see if the situation improves.
