### ISSUE TITLE
Write Pulumi Code for Kubernetes Cluster Deployment. 

### ISSUE THREAD

**Issue by mitangelo** [mitodl/ol-infrastructure#787]
This will involved writing production grade pulumi code for deploying kubernetes clusters on aws.

**Comment by mitangelo** [comment]
This should include the infrastructure setup as well as the base setup needed to make the cluster fully functional. We can discuss all the applications needed to do this when the time comes.

**Comment by blarghmatey** [comment]
After some exploratory work on Kubernetes we have decided that the overall effort is not worth the investment right now given our team capacity and competing priorities.
