### ISSUE TITLE
Renew and update MITx wildcard certificate

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#817]
The MITx wildcard certificate expires on June 30th, so we need to get an updated version of it. Once we have the new certificate we need to update the value in Vault and ACM to ensure that all of our assets deployed under mitx.mit.edu subdomains continue operating.

**Comment by Ardiea** [comment]
Followed http://kb.mit.edu/confluence/display/istcontrib/Obtaining+an+SSL+certificate+for+a+web+server and requested a new cert from IS&T. I generated a new key and uploaded it to keybase.

**Comment by Ardiea** [comment]
Fastly updated, though it was a little awkward?

**Comment by Ardiea** [comment]
replaced in secrets-mitx and secrets-mitx-staging in all vault envs, replaced in acm
