### ISSUE TITLE
Deploy and configure MFEs needed for Olive release

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#833]
Definitely want these:
- [x] Gradebook: https://github.com/openedx/frontend-app-gradebook/tree/open-release/nutmeg.master
- [x] Library authoring: https://github.com/openedx/frontend-app-library-authoring
  - [x] CI
    - [x] xPro
    - [x] Residential
  - [x] QA
    - [x] xPro
    - [x] Residential
  - [x] Production
    - [x] xPro
    - [x] Residential
- [ ] Course authoring: https://github.com/openedx/frontend-app-course-authoring
  - [x] CI
    - [x] xPro
    - [x] Residential
  - [x] QA
    - [x] xPro
    - [x] Residential
  - [x] Production
    - [x] xPro
    - [x] Residential
- [ ] ORA Grading https://github.com/edx/frontend-app-ora-grading
  - [x] CI
    - [x] xPro
    - [x] Residential
  - [ ] QA
    - [ ] xPro
    - [ ] Residential
  - [ ] Production
    - [ ] xPro
    - [ ] Residential

Probably don't want these: 
- [ ] Discussion https://github.com/openedx/frontend-app-discussions
- [ ] Communications https://github.com/edx/frontend-app-communications

Definitely don't need these:
- [ ] Authentication https://github.com/openedx/frontend-app-authn 
- [ ] Learner Dashboard https://github.comedx/frontend-app-learner-dashboard

**Comment by blarghmatey** [comment]
This is a good opportunity to address #750 as well

**Comment by blarghmatey** [comment]
@pdpinch the gradebook and library MFEs are now being built but will still need some configuration added to edx-platform. Can you update this ticket with priorities/timeliness of the other MFEs? Getting them built and deployed is now straightforward with the new Concourse pipeline templates. The open question for each of them is what the integration steps look like on the edx-platform side.

**Comment by blarghmatey** [comment]
The gradebook MFE has been deployed to all environments and all installations.

**Comment by pdpinch** [comment]
more discussions about olive MFEs are at https://docs.google.com/document/d/1Q4K2FSd5HUpsLi5H6oG-43QNfuc9AJ1cVWKkNZqYi4w/edit#

**Comment by blarghmatey** [comment]
Adding a note here that in the first pass the `new_core_editors.use_new_problem_editor` flag seems to result in a broken experience. Clicking on the edit button for a problem loads the MFE with the only visible component being the text `"Problem"`
