### ISSUE TITLE
Migrate codejail usage in edx-platform to use web service

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#834]
As more of the edX ecosystem migrates to containers it introduces a challenge with managing safe execution of user-submitted code. To address that challenge the folks at eduNEXT created a web service to wrap the codejail project so that it can be decoupled from the edx-platform runtime. We would like to start using that service for our own deployments so that we can validate its functionality ahead of our shift to a containerized edx-platform deployment.

- [ ] Deploy a test instance of the eduNEXT codejail service https://github.com/eduNEXT/codejailservice/
- [ ] Configure one of our installations of edx-platform to use the codejail service instead of the local apparmor environment
- [ ] Identify any failures or edge cases that we will need to address and file them as issues to be resolved.

**Comment by amendoncbh** [comment]
Will create a pipeline for https://github.com/openedx/codejail - docker image build.
