### ISSUE TITLE
Deploy Open edX forum using Docker compose

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/ol-infrastructure#868]
# User Story
- As a platform operator I would like to be able to deploy the Open edX forum as a standalone service

# Description/Context
We currently deploy the Forum service as part of the EC2 instance that runs both edx-platform and Xqueue. This means that it is not possible to size and scale each service according to its usage. It also means that we are not able to compartmentalize the steps involved in building and configuring each service. Now that we have a pipeline for building the Forum service as a docker image we would like to run it with docker-compose on the baseline image that we built to accomodate that deployment model.

# Acceptance Criteria
- [x] #873
- [x] #874
- [x] #875
- [x] #876
- [x] #877

**Comment by mitangelo** [comment]
@blarghmatey Do you have sometime to discuss this issue?
