### ISSUE TITLE
OCW: redirect `/resources/res-` instead of `resources`

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#871]
# User Story

As a course author, I need to add a resource (e.g. a PDF) to a page on the `ocw-www` site. 

Resources pages are published in the `resources` directory, but that is currently getting redirected to `courses` to maintain legacy URLs. 

# Description/Context

The legacy URLs that need to be redirected all start with `resources/res-`, so the redirect could be refined so it doesn't interfere with these newly-published pages. 

# Acceptance Criteria
- [x] on RC, confirm the new published URL https://live-qa.ocw.mit.edu/resources/clinton-blackburn/index.html works and doesn't get redirected to a URL that returns a 404. 
- [ ] Confirm the legacy URL https://ocw.mit.edu/resources/res-10-s95-physics-of-covid-19-transmission-fall-2020/ still redirects to https://ocw.mit.edu/courses/res-10-s95-physics-of-covid-19-transmission-fall-2020/

**Comment by pdpinch** [comment]
Ok. Couldn't figure out why this wasn't working for me, and then I realized I @#$@#$-ed up the acceptance criteria. After I updated the acceptance criteria, all is good:

These all work as expected: 

```
curl -I https://draft-qa.ocw.mit.edu/resources/clinton-blackburn/
HTTP/2 200 
```

```
curl -I https://draft-qa.ocw.mit.edu/resources/res-10-s95-physics-of-covid-19-transmission-fall-2020/
HTTP/2 302 
retry-after: 0
location: /courses/res-10-s95-physics-of-covid-19-transmission-fall-2020/
```

```
curl -I https://live-qa.ocw.mit.edu/resources/clinton-blackburn/index.html
HTTP/2 200 
```

```
curl -I https://live-qa.ocw.mit.edu/resources/res-10-s95-physics-of-covid-19-transmission-fall-2020/index.html
HTTP/2 302 
retry-after: 0
location: /courses/res-10-s95-physics-of-covid-19-transmission-fall-2020/index.html
```

Please deploy at your convenience.

**Comment by shaidar** [comment]
That should be deployed on production now

**Comment by pdpinch** [comment]
I'm pretty sure this is working now. For example, https://ocw.mit.edu/resources/20_years_of_ocw_impact/ returns a 200
