### ISSUE TITLE
OCW: http://ocw.mit.edu/ should redirect to https://ocw.mit.edu/ (draft and production) 

### ISSUE THREAD

**Issue by pdpinch** [mitodl/ol-infrastructure#905]
# User Story
- Sometimes users (or apps, like Slack) forget to include the protocol when sharing links.

The user of the shared link can arrive at an `http` URL, which should redirect to `https` 

# Description/Context

This is the current response header I get:

```
pdpinch@pdpinch2018 ~ % curl -I http://draft.ocw.mit.edu/
HTTP/1.1 404 Moved Permanently
Retry-After: 0
Location: https://draft.ocw.mit.edu/
Content-Length: 0
Accept-Ranges: bytes
Date: Wed, 15 Jun 2022 15:19:05 GMT
Connection: close
X-Served-By: cache-lga21944-LGA
X-Cache: HIT
X-Cache-Hits: 0
```

It seems like some browsers are confused by the mismatch between the response code `404` and the response header `Moved Permanently`

**Comment by pdpinch** [comment]
I updated the title because this affects production as well as draft servers.

**Comment by shaidar** [comment]
This is deployed on QA now

**Comment by shaidar** [comment]
This is hitting [this](https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/ocw_site/snippets/redirects.vcl#L41-L50) and then hits [this](https://github.com/mitodl/ol-infrastructure/blob/main/src/ol_infrastructure/applications/ocw_site/snippets/reroute_redirects.vcl#L1-L5). We should be able to "word" it however way we want if that's an issue
